spring:
  thymeleaf:
    cache: false
  mvc:
    locale: es
  datasource:
    url: jdbc:h2:mem:DB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /console
  profiles:
    active: development

environments:
  development:
    url: http://db.developer.com
    name: Developer Database
  production:
    url: http://db.production.com
    name: Production Database